config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  get "/profile", to: "users#show", as: :user

  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "sessions#create"

  delete "/logout", to: "sessions#destroy", as: :logout

end

app/models/message.rb
class Message < OpenStruct

  def self.service
    @service ||= GoogleService.new
  end

  def self.all
    service.messages.map { |msg| new(msg) }
  end

  def self.format
    all.map {|msg| msg.id}
  end

  def self.inbox
    format.map {|id| service.message(id)}.slice(0..5)
    # binding.pry
  end

  # def senders_email
  #   ["payload"]["headers"][15].fetch("value").match("(<[^>]+>)")[1].gsub("<","").gsub(">","")
  # end

  def from(message)
      message["payload"]["headers"][15].fetch("value").match("(<[^>]+>)")[1].gsub("<","").gsub(">","")
  end

  # def time_recieved
  #   ["payload"]["headers"][7].fetch("value").split(";")[1]
  # end

  def time
    inbox.map do |message|
       message["payload"]["headers"][7].fetch("value").split(";")[1]
     end
  end

  # def subject
  #   # ["payload"]["headers"][17]#.fetch("value").split(";")[1]
  #   ["payload"]["headers"].keep_if do |header|
  #     header["name"] == "Subject"
  #   end.first["value"]
  # end

  def about
    inbox.map do |message|
        message["payload"]["headers"].keep_if do |header|
          header["name"] == "Subject"
      end.first["value"]
    end
  end

  # def list
  #   payload["headers"]#.fetch("value").split(";")[1]
  # end

  def self.find(id)
    Message.new(service.message(id))
  end
end
# binding.pry

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :format_first_name

  def self.from_omniauth(auth_hash)
    # binding.pry
    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    user.name = auth_hash['info']['name']
    user.location = auth_hash['info']['location']
    user.image_url = auth_hash['info']['image']
    user.oauth_token = auth_hash['credentials']['token']
    user.url = auth_hash['info']['urls'][user.provider.capitalize]
    user.save!
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.format
  end

  def show
    @message = Message.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include ApplicationHelper

  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # def create
  #   @user = User.find_or_create_from_auth_hash(auth_hash)
  #   self.current_user = @user
  #   redirect_to '/'
  # end

  def create
    auth = request.env["omniauth.auth"]
    if user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
      session[:user_id] = user.id
      redirect_to user_path(user.username)
    else
      redirect_to root_path
    end
  end

  def destroy
    if current_user
      session.delete(:user_id)
      flash[:success] = 'Come back soon you will!'
    end
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

end

  # def create
  #   begin
  #     @user = User.from_omniauth(request.env['omniauth.auth'])
  #     session[:user_id] = @user.id
  #     flash[:success] = "Welcome, #{@user.name}!"
  #   rescue
  #     flash[:warning] = "An error there was while trying to authenticate you..."
  #   end
  #   redirect_to root_path
  # end
  #
  #
  # def destroy
  #   if current_user
  #     session.delete(:user_id)
  #     flash[:success] = 'Come back soon you will!'
  #   end
  #   redirect_to root_path
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @name = format_first_name(@user.name)
    # @messages = Message.all
    @inbox = Message.inbox
  end

private

  def set_user
    @user = User.find_by(id: session[:user_id])
  end

  def format_first_name(name)
    name.split.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>ApiCuriousFoss</title>

  <!DOCTYPE html>
  <html lang="en">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Api Curious Foss Foss</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/grayscale.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "shared/navbar" %>

<%= yield %>

<!-- Footer -->
<!-- <footer>
    <div class="container text-center">
        <p>Copyright &copy; Your Website 2014</p>
    </div>
</footer> -->

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="js/jquery.easing.min.js"></script>

<!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

<!-- Custom Theme JavaScript -->
<script src="js/grayscale.js"></script>

<!-- The top of file index.html -->
<html itemscope itemtype="http://schema.org/Article">
<head>
  <!-- BEGIN Pre-requisites -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
  </script>
  <script src="https://apis.google.com/js/client:platform.js?onload=start" async defer>
  </script>

</body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<% @messages.each do |message| %>
  <p>
    <%= message %>
  </p>
<% end %>

app/views/messages/show.html.erb
<br>
<br>
<br>
<br>
<br>

<h1>Specific Message</h1>

<p>An email you have from: 
  <%= @message.senders_email %>
</p>

<p>Sent it was at:
  <%= @message.time_recieved %>
</p>

<p>About it is:
  <%= @message.subject %>
</p>

<!-- <p>
  <ol>
  <%# @message.list.each do |header| %>

      <li><%#= header %></li>
      <%# end %>
    </ol>
</p> -->

app/views/pages/extra.html.erb
<!-- About Section -->
<!-- <section id="about" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>About Grayscale</h2>
            <p>Grayscale is a free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, simply download the template on <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
            <p>This theme features stock photos by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
            <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with LESS files for easy customization.</p>
        </div>
    </div>
</section> -->
<!-- ROUND BUTTON -->

<a href="#about" class="btn btn-circle page-scroll">
    <i class="fa fa-angle-double-down animated"></i>
</a>


<!-- Download Section -->
<section id="download" class="content-section text-center">
    <div class="download-section">
        <div class="container">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Download Grayscale</h2>
                <p>You can download Grayscale for free on the preview page at Start Bootstrap.</p>
                <a href="http://startbootstrap.com/template-overviews/grayscale/" class="btn btn-default btn-lg">Visit Download Page</a>
            </div>
        </div>
    </div>
</section>

<!-- Contact Section -->
<section id="contact" class="container content-section text-center">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
            <h2>Contact Start Bootstrap</h2>
            <p>Feel free to email us to provide some feedback on our templates, give us suggestions for new templates and themes, or to just say hello!</p>
            <p><a href="mailto:feedback@startbootstrap.com">feedback@startbootstrap.com</a>
            </p>
            <ul class="list-inline banner-social-buttons">
                <li>
                    <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                </li>
                <li>
                    <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                </li>
                <li>
                    <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                </li>
            </ul>
        </div>
    </div>
</section>

<!-- Map Section -->
<div id="map"></div>

app/views/pages/home.html.erb
    <!-- Intro Header -->
    <header class="intro home">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">

                        <% flash.each do |type, message| %>
                          <%= content_tag :div, message.html_safe, class: "#{type} flashy", id: "flash_notice" %>
                        <% end %>
                        <h1 class="brand-heading">Tough Love</h1>
                        <p class="intro-text">Because sometimes you need it.<br>Someone on your shoulder to tell it like it is.</p>

                    </div>
                </div>
            </div>
        </div>
    </header>

app/views/shared/_navbar.html.erb
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
        <i class="fa fa-bars"></i>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top">
        <i class="fa fa-play-circle"></i>  <span class="light">I'm good at this<a class="page-scroll" href="https://www.linkedin.com/in/kris-foss-a9683617">Hire Me</a></span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
      <ul class="nav navbar-nav">
        <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <% if current_user %>
          Hello, <%= current_user.name %>
        <% else %>
        <li>
          <%#= link_to "Login with Google+", google_login_path %>
          <%#= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %>
          <li><%= link_to 'Login With Github', github_login_path %></li>
        </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/users/show.html.erb
<!-- About Section -->
<section id="about" class="container content-section text-left dash" id="dash">
    <div class="row">
        <!-- <div class="col-lg-8 col-lg-offset-2"> -->
            <div class="dash">
              <h2>Hi <%= @name %></h2>

              <%= image_tag @user.image_url, class: "img-circle dashb", width: "200px" %>
            </div>

            <div class="email-list">
              <table class="table table-striped sized-table">
                <tr>
                  <th>
                    <h4>From:</h4>
                  </th>
                  <th>
                    <h4>Subject:</h4>
                  </th>
                  <th>
                    <h4>Time Recieved:</h4>
                  </th>
                </tr>
                <% @inbox.each do |message| %>
                <%#= binding.pry %>
                <tr>
                  <td>
                    <!-- <h4><%#= message["payload"]["headers"][15].fetch("value").match("(<[^>]+>)")[1].gsub("<","").gsub(">","") %></h4> -->
                    <h4><%= message["payload"]["headers"].keep_if {|header| header["name"] == "From"}.first["value"] .match("(<[^>]+>)")[1].gsub("<","").gsub(">","") %></h4>
                  </td>
                  <td>
                    <h4><%= message["payload"]["headers"].keep_if {|header| header["name"] == "Subject"}.first["value"] %></h4>
                  </td>
                  <td>
                    <!-- <h4><%#= message["payload"]["headers"][7].fetch("value").split(";")[1] %></h4> -->
                    <h4><%= message["payload"]["headers"].keep_if {|header| header["name"] == "Date"}.first["value"] %></h4>
                  </td>
              </tr>
              <% end %>

              </table>
              <%#= @user. %>
            </div>

            <%#= @inbox %>
            <!-- <p>Grayscale is a free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, simply download the template on <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
            <p>This theme features stock photos by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
            <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with LESS files for easy customization.</p> -->
        <!-- </div> -->
    </div>
</section>